name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore: [ "LICENSE", "index.js", "README.md" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install

      - name: "Run Jest tests with coverage"
        env:
          DETA_BASE_NAME: ${{ secrets.DETA_BASE_NAME }}
          DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
        run: pnpm jest tests --ci --coverage

      - name: "Upload coverage report to Codecov"
        uses: codecov/codecov-action@v3

        timeout-minutes: 30
